version: "3"
services:
  app:
    build:
      dockerfile: ./python-dockerfile/Dockerfile
    volumes:
      - ./src:/code
    working_dir: /code
    tty: true
    command: "/bin/bash"
    container_name: app

    # First start the container
    # docker-compose up -d

    # EDit file then run the python script
    # docker-compose exec app bash -c "python3 main.py"